package projectwarnet;

import java.util.Calendar;
import java.awt.Color;
import java.awt.HeadlessException;
import java.awt.Window;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.sql.Connection;
import java.sql.Time;
import java.util.Date;
import java.sql.Timestamp;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.plaf.ComboBoxUI;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author Reyhan Al Farel
 */
public class Admin extends javax.swing.JFrame {
    
    public static Statement stm;
    public static ResultSet res;
    /**
     * Creates new form Admin
     */
    public Admin() {
        initComponents();
        jTextField1.setVisible(false);
        jTextField_SearchMember.setVisible(false);
        jButton_Cari.setVisible(false);
        // Buat Member
        jButton_BuatMember.setVisible(false);
        jButton_BackBuatMember.setVisible(false);
        jButton_BuatMember_2.setVisible(false);
        jScrollPane_NamaMember.setVisible(false);
        jTextField_UsernameMember.setVisible(false);
        jPasswordField_BuatMember.setVisible(false);
        jPasswordField_KonfirmasiPasswordMember.setVisible(false);
        jScrollPane_Transaksi.setVisible(false);
        
        jPanel_JikaPilihAccount.setVisible(false);
        jPanel_JikaPilihTransaksi.setVisible(false);
        
        
        jPanel_BuatMember.setVisible(false);
        jPanel_GantiPassword.setVisible(false);
        jPanel_TambahWaktu.setVisible(false);
    }
    
    public void tampilanMember() {
        DefaultTableModel tb = new DefaultTableModel();
        tb.addColumn("Username");
        tb.addColumn("Harga");
        tb.addColumn("Waktu");
        jTable_NamaMember.setModel(tb);
        
        String cari = jTextField_SearchMember.getText();
        
        try {
            String sql = "SELECT * FROM tbl_akun WHERE Username LIKE'%"+cari+"%'";
            java.sql.Connection conn = (Connection) KoneksiDataMember.configDB();
            java.sql.PreparedStatement pst = conn.prepareStatement(sql);
            ResultSet result = pst.executeQuery();
            while (result.next()) {
                tb.addRow(new Object[] {
                result.getString("Username"),
                result.getDouble("Harga"),
                result.getTime("Waktu"),
                });
            }
            
        } catch(Exception e) {
            JOptionPane.showMessageDialog(null, "Data Gagal Ditampilkan");
        }
        
    }
    
    public void tampilanTransaksi() {
       DefaultTableModel tb = new DefaultTableModel();
        tb.addColumn("Tanggal");
        tb.addColumn("Username");
        tb.addColumn("Harga");
        tb.addColumn("Waktu");
        jTable_Transaksi.setModel(tb);
        
        try {
            String sql = "SELECT * FROM tbl_transaksi";
            java.sql.Connection conn = (Connection) KoneksiDataMember.configDB();
            java.sql.PreparedStatement pst = conn.prepareStatement(sql);
            ResultSet result = pst.executeQuery();
            while (result.next()) {
                tb.addRow(new Object[] {
                result.getTimestamp("Tanggal"),
                result.getString("Username"),
                result.getDouble("Harga"),
                result.getTime("Waktu"),
                });
            }
            
        } catch(Exception e) {
            JOptionPane.showMessageDialog(null, "Data Gagal Ditampilkan");
        } 
    }
    
    public void jumlahTransaksi() {
        try {
            String selectHargaSql = "SELECT SUM(Harga) AS TotalHarga FROM tbl_transaksi";
            java.sql.Connection conn = (Connection) KoneksiDataMember.configDB();
            java.sql.PreparedStatement statement = conn.prepareStatement(selectHargaSql);
            ResultSet rs = statement.executeQuery();

            if (rs.next()) {
                double totalHarga = rs.getDouble("TotalHarga");
                String totalHargaString = String.valueOf(totalHarga);
                jLabel_HargaTransaksi.setText("Rp. "+totalHargaString);
    
            } else {
                System.out.println("Data Harga tidak ditemukan");
            }

            rs.close();
            statement.close();
        
        } catch (Exception e) {
            System.out.println("Data Gagal Ditampilkan");
        }

    }
   
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel_HeaderAdminWarnet = new javax.swing.JPanel();
        jPanel_Komputer = new javax.swing.JPanel();
        jLabel_TulisanKomputer = new javax.swing.JLabel();
        jPanel_Account = new javax.swing.JPanel();
        jLabel_TulisanAccount = new javax.swing.JLabel();
        jPanel_Transaksi = new javax.swing.JPanel();
        jLabel_TulisanTransaksi = new javax.swing.JLabel();
        jButton_Logout = new javax.swing.JButton();
        jPanel_PendapatanHarian = new javax.swing.JPanel();
        jLabel_DetailPc = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jPanel_SearchNamaMember = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        jTextField_SearchMember = new javax.swing.JTextField();
        jButton_Cari = new javax.swing.JButton();
        jPanel_JikaPilihKomputer = new javax.swing.JPanel();
        jPanel_Pc01 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jPanel_Pc02 = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jPanel_Pc03 = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        jPanel_Pc04 = new javax.swing.JPanel();
        jLabel24 = new javax.swing.JLabel();
        jPanel_Pc05 = new javax.swing.JPanel();
        jLabel25 = new javax.swing.JLabel();
        jPanel_Pc06 = new javax.swing.JPanel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jPanel_Pc07 = new javax.swing.JPanel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jPanel_Pc13 = new javax.swing.JPanel();
        jLabel49 = new javax.swing.JLabel();
        jPanel_Pc08 = new javax.swing.JPanel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jPanel_Pc09 = new javax.swing.JPanel();
        jLabel38 = new javax.swing.JLabel();
        jPanel_Pc10 = new javax.swing.JPanel();
        jLabel39 = new javax.swing.JLabel();
        jPanel_Pc11 = new javax.swing.JPanel();
        jLabel40 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        jPanel_Pc12 = new javax.swing.JPanel();
        jLabel44 = new javax.swing.JLabel();
        jLabel45 = new javax.swing.JLabel();
        jLabel46 = new javax.swing.JLabel();
        jLabel47 = new javax.swing.JLabel();
        jPanel_Pc14 = new javax.swing.JPanel();
        jLabel50 = new javax.swing.JLabel();
        jPanel_Pc15 = new javax.swing.JPanel();
        jLabel48 = new javax.swing.JLabel();
        jLabel54 = new javax.swing.JLabel();
        jLabel55 = new javax.swing.JLabel();
        jLabel56 = new javax.swing.JLabel();
        jPanel_Pc16 = new javax.swing.JPanel();
        jLabel51 = new javax.swing.JLabel();
        jLabel57 = new javax.swing.JLabel();
        jLabel58 = new javax.swing.JLabel();
        jLabel59 = new javax.swing.JLabel();
        jPanel_Pc17 = new javax.swing.JPanel();
        jLabel52 = new javax.swing.JLabel();
        jLabel60 = new javax.swing.JLabel();
        jLabel61 = new javax.swing.JLabel();
        jLabel62 = new javax.swing.JLabel();
        jPanel_Pc18 = new javax.swing.JPanel();
        jLabel53 = new javax.swing.JLabel();
        jLabel63 = new javax.swing.JLabel();
        jLabel64 = new javax.swing.JLabel();
        jLabel65 = new javax.swing.JLabel();
        jPanel_JikaPilihAccount = new javax.swing.JPanel();
        jScrollPane_NamaMember = new javax.swing.JScrollPane();
        jTable_NamaMember = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jLabel66 = new javax.swing.JLabel();
        jButton_BuatMember = new javax.swing.JButton();
        jPanel_BuatMember = new javax.swing.JPanel();
        jButton_BackBuatMember = new javax.swing.JButton();
        jLabel67 = new javax.swing.JLabel();
        jTextField_UsernameMember = new javax.swing.JTextField();
        jLabel68 = new javax.swing.JLabel();
        jLabel69 = new javax.swing.JLabel();
        jLabel70 = new javax.swing.JLabel();
        jButton_BuatMember_2 = new javax.swing.JButton();
        jPasswordField_BuatMember = new javax.swing.JPasswordField();
        jPasswordField_KonfirmasiPasswordMember = new javax.swing.JPasswordField();
        jButton_GantiPassword = new javax.swing.JButton();
        jPanel_GantiPassword = new javax.swing.JPanel();
        jLabel73 = new javax.swing.JLabel();
        jLabel74 = new javax.swing.JLabel();
        jTextField_UsernameGantiPassword = new javax.swing.JTextField();
        jLabel75 = new javax.swing.JLabel();
        jPasswordField_PasswordLamaGantiPassword = new javax.swing.JPasswordField();
        jLabel76 = new javax.swing.JLabel();
        jPasswordField_PasswordBaruGantiPassword = new javax.swing.JPasswordField();
        jButton_GantiPassword_2 = new javax.swing.JButton();
        jButton_BackGantiPassword = new javax.swing.JButton();
        jPanel_TambahWaktu = new javax.swing.JPanel();
        jLabel77 = new javax.swing.JLabel();
        jTextField_UsernameTambahWaktu = new javax.swing.JTextField();
        jLabel78 = new javax.swing.JLabel();
        jComboBox_Paket = new javax.swing.JComboBox<>();
        jLabel79 = new javax.swing.JLabel();
        jLabel80 = new javax.swing.JLabel();
        jTextField_HargaTambahWaktu = new javax.swing.JTextField();
        jButton_IsiWaktu = new javax.swing.JButton();
        jButton_BackTambahWaktu = new javax.swing.JButton();
        jPanel_JikaPilihTransaksi = new javax.swing.JPanel();
        jScrollPane_Transaksi = new javax.swing.JScrollPane();
        jTable_Transaksi = new javax.swing.JTable();
        jLabel71 = new javax.swing.JLabel();
        jLabel_HargaTransaksi = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1000, 600));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel_HeaderAdminWarnet.setBackground(new java.awt.Color(48, 119, 167));
        jPanel_HeaderAdminWarnet.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel_Komputer.setBackground(new java.awt.Color(48, 119, 167));
        jPanel_Komputer.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel_TulisanKomputer.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel_TulisanKomputer.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_TulisanKomputer.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_TulisanKomputer.setText("Komputer");
        jLabel_TulisanKomputer.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel_TulisanKomputer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_TulisanKomputerMouseClicked(evt);
            }
        });
        jPanel_Komputer.add(jLabel_TulisanKomputer, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, 180, 40));

        jPanel_HeaderAdminWarnet.add(jPanel_Komputer, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 0, 260, 60));

        jPanel_Account.setBackground(new java.awt.Color(48, 119, 167));
        jPanel_Account.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel_TulisanAccount.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel_TulisanAccount.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_TulisanAccount.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_TulisanAccount.setText("Account");
        jLabel_TulisanAccount.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel_TulisanAccount.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_TulisanAccountMouseClicked(evt);
            }
        });
        jPanel_Account.add(jLabel_TulisanAccount, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, 180, 40));

        jPanel_HeaderAdminWarnet.add(jPanel_Account, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 0, 260, 60));

        jPanel_Transaksi.setBackground(new java.awt.Color(48, 119, 167));
        jPanel_Transaksi.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel_TulisanTransaksi.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel_TulisanTransaksi.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_TulisanTransaksi.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_TulisanTransaksi.setText("Transaksi");
        jLabel_TulisanTransaksi.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel_TulisanTransaksi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_TulisanTransaksiMouseClicked(evt);
            }
        });
        jPanel_Transaksi.add(jLabel_TulisanTransaksi, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, 180, 40));

        jPanel_HeaderAdminWarnet.add(jPanel_Transaksi, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 0, 260, 60));

        jButton_Logout.setBackground(new java.awt.Color(255, 51, 51));
        jButton_Logout.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton_Logout.setForeground(new java.awt.Color(255, 255, 255));
        jButton_Logout.setText("Log out");
        jButton_Logout.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton_Logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_LogoutActionPerformed(evt);
            }
        });
        jPanel_HeaderAdminWarnet.add(jButton_Logout, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 130, -1));

        jPanel1.add(jPanel_HeaderAdminWarnet, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 60));

        jPanel_PendapatanHarian.setBackground(new java.awt.Color(27, 30, 37));
        jPanel_PendapatanHarian.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel_DetailPc.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_DetailPc.setText("Detail PC");
        jLabel_DetailPc.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(255, 255, 255)));
        jPanel_PendapatanHarian.add(jLabel_DetailPc, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 200, 30));

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Intel Core i9-13900K Raptor Lake");
        jPanel_PendapatanHarian.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 200, 20));

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Nvidia RTX 3080 TI");
        jPanel_PendapatanHarian.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 200, -1));

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Kingstone Fury Beast 16 GB");
        jPanel_PendapatanHarian.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 200, -1));

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Ssd Nvme Samsung Evo 970 1TB");
        jPanel_PendapatanHarian.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, 200, -1));

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Psu ROG Strix 1000 W 80+");
        jPanel_PendapatanHarian.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, 200, -1));

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Asus ROG Maximus Z690 Apex");
        jPanel_PendapatanHarian.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 200, -1));

        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Harga Waktu");
        jLabel7.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(255, 255, 255)));
        jPanel_PendapatanHarian.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, 200, 30));

        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Paket 1 Jam                 : Rp. 10.000");
        jPanel_PendapatanHarian.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 310, 200, -1));

        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Paket 2 Jam                 : Rp. 18.000");
        jPanel_PendapatanHarian.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 330, 200, -1));

        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Paket 3 Jam                 : Rp. 25.000");
        jPanel_PendapatanHarian.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 350, 200, -1));

        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Paket 5 Jam                 : Rp. 35.000");
        jPanel_PendapatanHarian.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 370, 200, -1));

        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Paket 10 Jam               : Rp. 50.000");
        jPanel_PendapatanHarian.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 390, 200, -1));

        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Paket Malam                : Rp. 40.000");
        jPanel_PendapatanHarian.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 410, 200, -1));

        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("(Dari 09:00 PM – 04:00 AM)");
        jPanel_PendapatanHarian.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 430, 200, -1));

        jPanel1.add(jPanel_PendapatanHarian, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 220, 540));

        jPanel_SearchNamaMember.setBackground(new java.awt.Color(27, 30, 37));
        jPanel_SearchNamaMember.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextField1.setEditable(false);
        jTextField1.setBackground(new java.awt.Color(255, 255, 255));
        jTextField1.setText("Nama Member");
        jTextField1.setName(""); // NOI18N
        jPanel_SearchNamaMember.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 160, -1));

        jTextField_SearchMember.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField_SearchMemberKeyReleased(evt);
            }
        });
        jPanel_SearchNamaMember.add(jTextField_SearchMember, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 105, 160, -1));

        jButton_Cari.setText("Cari");
        jPanel_SearchNamaMember.add(jButton_Cari, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 150, -1, -1));

        jPanel1.add(jPanel_SearchNamaMember, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 220, 540));

        jPanel_JikaPilihKomputer.setBackground(new java.awt.Color(57, 61, 62));
        jPanel_JikaPilihKomputer.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel_Pc01.setBackground(new java.awt.Color(59, 81, 120));
        jPanel_Pc01.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("PC – 01");
        jPanel_Pc01.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 110, 20));

        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("5j 34m");
        jPanel_Pc01.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 110, -1));

        jLabel17.setForeground(new java.awt.Color(255, 204, 51));
        jLabel17.setText(" Dota 2");
        jPanel_Pc01.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 110, -1));

        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8-money-48.png"))); // NOI18N
        jPanel_Pc01.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 50, 40, 40));

        jPanel_JikaPilihKomputer.add(jPanel_Pc01, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 110, 120));

        jPanel_Pc02.setBackground(new java.awt.Color(59, 81, 120));
        jPanel_Pc02.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel19.setText("PC – 02");
        jPanel_Pc02.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 110, 20));

        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText("1j 41m");
        jPanel_Pc02.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 110, -1));

        jLabel22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8-money-48.png"))); // NOI18N
        jPanel_Pc02.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 50, 40, 40));

        jLabel23.setForeground(new java.awt.Color(255, 204, 51));
        jLabel23.setText(" LostSaga");
        jPanel_Pc02.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 110, -1));

        jPanel_JikaPilihKomputer.add(jPanel_Pc02, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 30, 110, 120));

        jPanel_Pc03.setBackground(new java.awt.Color(28, 31, 38));
        jPanel_Pc03.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel20.setText("PC – 03");
        jPanel_Pc03.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 110, 20));

        jPanel_JikaPilihKomputer.add(jPanel_Pc03, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 30, 110, 120));

        jPanel_Pc04.setBackground(new java.awt.Color(28, 31, 38));
        jPanel_Pc04.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel24.setForeground(new java.awt.Color(255, 255, 255));
        jLabel24.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel24.setText("PC – 04");
        jPanel_Pc04.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 110, 20));

        jPanel_JikaPilihKomputer.add(jPanel_Pc04, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 30, 110, 120));

        jPanel_Pc05.setBackground(new java.awt.Color(28, 31, 38));
        jPanel_Pc05.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel25.setForeground(new java.awt.Color(255, 255, 255));
        jLabel25.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel25.setText("PC – 05");
        jPanel_Pc05.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 110, 20));

        jPanel_JikaPilihKomputer.add(jPanel_Pc05, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 30, 110, 120));

        jPanel_Pc06.setBackground(new java.awt.Color(59, 81, 120));
        jPanel_Pc06.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel26.setForeground(new java.awt.Color(255, 255, 255));
        jLabel26.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel26.setText("PC – 06");
        jPanel_Pc06.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 110, 20));

        jLabel27.setForeground(new java.awt.Color(255, 255, 255));
        jLabel27.setText("0j 20m");
        jPanel_Pc06.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 110, -1));

        jLabel28.setForeground(new java.awt.Color(255, 204, 51));
        jLabel28.setText(" Moto Gp 2");
        jPanel_Pc06.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 110, -1));

        jLabel29.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8-money-48.png"))); // NOI18N
        jPanel_Pc06.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 50, 40, 40));

        jPanel_JikaPilihKomputer.add(jPanel_Pc06, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 30, 110, 120));

        jPanel_Pc07.setBackground(new java.awt.Color(59, 81, 120));
        jPanel_Pc07.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel30.setForeground(new java.awt.Color(255, 255, 255));
        jLabel30.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel30.setText("PC – 07");
        jPanel_Pc07.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 110, 20));

        jLabel31.setForeground(new java.awt.Color(255, 255, 255));
        jLabel31.setText("3j 10m");
        jPanel_Pc07.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 110, -1));

        jLabel32.setForeground(new java.awt.Color(255, 204, 51));
        jLabel32.setText(" Fortnite");
        jPanel_Pc07.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 110, -1));

        jLabel33.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8-money-48.png"))); // NOI18N
        jPanel_Pc07.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 50, 40, 40));

        jPanel_JikaPilihKomputer.add(jPanel_Pc07, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, 110, 120));

        jPanel_Pc13.setBackground(new java.awt.Color(28, 31, 38));
        jPanel_Pc13.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel49.setForeground(new java.awt.Color(255, 255, 255));
        jLabel49.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel49.setText("PC – 13");
        jPanel_Pc13.add(jLabel49, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 110, 20));

        jPanel_JikaPilihKomputer.add(jPanel_Pc13, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 350, 110, 120));

        jPanel_Pc08.setBackground(new java.awt.Color(59, 81, 120));
        jPanel_Pc08.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel34.setForeground(new java.awt.Color(255, 255, 255));
        jLabel34.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel34.setText("PC – 08");
        jPanel_Pc08.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 110, 20));

        jLabel35.setForeground(new java.awt.Color(255, 255, 255));
        jLabel35.setText("1j 34m");
        jPanel_Pc08.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 110, -1));

        jLabel36.setForeground(new java.awt.Color(255, 204, 51));
        jLabel36.setText(" Among Us");
        jPanel_Pc08.add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 110, -1));

        jLabel37.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8-money-48.png"))); // NOI18N
        jPanel_Pc08.add(jLabel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 50, 40, 40));

        jPanel_JikaPilihKomputer.add(jPanel_Pc08, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 190, 110, 120));

        jPanel_Pc09.setBackground(new java.awt.Color(28, 31, 38));
        jPanel_Pc09.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel38.setForeground(new java.awt.Color(255, 255, 255));
        jLabel38.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel38.setText("PC – 09");
        jPanel_Pc09.add(jLabel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 110, 20));

        jPanel_JikaPilihKomputer.add(jPanel_Pc09, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 190, 110, 120));

        jPanel_Pc10.setBackground(new java.awt.Color(28, 31, 38));
        jPanel_Pc10.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel39.setForeground(new java.awt.Color(255, 255, 255));
        jLabel39.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel39.setText("PC – 10");
        jPanel_Pc10.add(jLabel39, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 110, 20));

        jPanel_JikaPilihKomputer.add(jPanel_Pc10, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 190, 110, 120));

        jPanel_Pc11.setBackground(new java.awt.Color(59, 81, 120));
        jPanel_Pc11.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel40.setForeground(new java.awt.Color(255, 255, 255));
        jLabel40.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel40.setText("PC – 11");
        jPanel_Pc11.add(jLabel40, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 110, 20));

        jLabel41.setForeground(new java.awt.Color(255, 255, 255));
        jLabel41.setText("2j 10m");
        jPanel_Pc11.add(jLabel41, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 110, -1));

        jLabel42.setForeground(new java.awt.Color(255, 204, 51));
        jLabel42.setText(" Left 4 Dead 2");
        jPanel_Pc11.add(jLabel42, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 110, -1));

        jLabel43.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8-money-48.png"))); // NOI18N
        jPanel_Pc11.add(jLabel43, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 50, 40, 40));

        jPanel_JikaPilihKomputer.add(jPanel_Pc11, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 190, 110, 120));

        jPanel_Pc12.setBackground(new java.awt.Color(59, 81, 120));
        jPanel_Pc12.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel44.setForeground(new java.awt.Color(255, 255, 255));
        jLabel44.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel44.setText("PC – 12");
        jPanel_Pc12.add(jLabel44, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 110, 20));

        jLabel45.setForeground(new java.awt.Color(255, 255, 255));
        jLabel45.setText("2j 10m");
        jPanel_Pc12.add(jLabel45, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 110, -1));

        jLabel46.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8-money-48.png"))); // NOI18N
        jPanel_Pc12.add(jLabel46, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 50, 40, 40));

        jLabel47.setForeground(new java.awt.Color(255, 204, 51));
        jLabel47.setText(" Left 4 Dead 2");
        jPanel_Pc12.add(jLabel47, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 110, -1));

        jPanel_JikaPilihKomputer.add(jPanel_Pc12, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 190, 110, 120));

        jPanel_Pc14.setBackground(new java.awt.Color(28, 31, 38));
        jPanel_Pc14.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel50.setForeground(new java.awt.Color(255, 255, 255));
        jLabel50.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel50.setText("PC – 14");
        jPanel_Pc14.add(jLabel50, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 110, 20));

        jPanel_JikaPilihKomputer.add(jPanel_Pc14, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 350, 110, 120));

        jPanel_Pc15.setBackground(new java.awt.Color(59, 81, 120));
        jPanel_Pc15.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel48.setForeground(new java.awt.Color(255, 255, 255));
        jLabel48.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel48.setText("PC – 15");
        jPanel_Pc15.add(jLabel48, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 110, 20));

        jLabel54.setForeground(new java.awt.Color(255, 255, 255));
        jLabel54.setText("5j 42m");
        jPanel_Pc15.add(jLabel54, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 110, -1));

        jLabel55.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8-money-48.png"))); // NOI18N
        jPanel_Pc15.add(jLabel55, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 50, 40, 40));

        jLabel56.setForeground(new java.awt.Color(255, 204, 51));
        jLabel56.setText(" Dota 2");
        jPanel_Pc15.add(jLabel56, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 110, -1));

        jPanel_JikaPilihKomputer.add(jPanel_Pc15, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 350, 110, 120));

        jPanel_Pc16.setBackground(new java.awt.Color(59, 81, 120));
        jPanel_Pc16.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel51.setForeground(new java.awt.Color(255, 255, 255));
        jLabel51.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel51.setText("PC – 16");
        jPanel_Pc16.add(jLabel51, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 110, 20));

        jLabel57.setForeground(new java.awt.Color(255, 255, 255));
        jLabel57.setText("6j 12m");
        jPanel_Pc16.add(jLabel57, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 110, -1));

        jLabel58.setForeground(new java.awt.Color(255, 204, 51));
        jLabel58.setText(" Dota 2");
        jPanel_Pc16.add(jLabel58, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 110, -1));

        jLabel59.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8-money-48.png"))); // NOI18N
        jPanel_Pc16.add(jLabel59, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 50, 40, 40));

        jPanel_JikaPilihKomputer.add(jPanel_Pc16, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 350, 110, 120));

        jPanel_Pc17.setBackground(new java.awt.Color(59, 81, 120));
        jPanel_Pc17.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel52.setForeground(new java.awt.Color(255, 255, 255));
        jLabel52.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel52.setText("PC – 17");
        jPanel_Pc17.add(jLabel52, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 110, 20));

        jLabel60.setForeground(new java.awt.Color(255, 255, 255));
        jLabel60.setText("3j 52m");
        jPanel_Pc17.add(jLabel60, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 110, -1));

        jLabel61.setForeground(new java.awt.Color(255, 204, 51));
        jLabel61.setText(" Dota 2");
        jPanel_Pc17.add(jLabel61, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 110, -1));

        jLabel62.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8-money-48.png"))); // NOI18N
        jPanel_Pc17.add(jLabel62, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 50, 40, 40));

        jPanel_JikaPilihKomputer.add(jPanel_Pc17, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 350, 110, 120));

        jPanel_Pc18.setBackground(new java.awt.Color(59, 81, 120));
        jPanel_Pc18.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel53.setForeground(new java.awt.Color(255, 255, 255));
        jLabel53.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel53.setText("PC – 18");
        jPanel_Pc18.add(jLabel53, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 110, 20));

        jLabel63.setForeground(new java.awt.Color(255, 255, 255));
        jLabel63.setText("9j 32m");
        jPanel_Pc18.add(jLabel63, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 110, -1));

        jLabel64.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8-money-48.png"))); // NOI18N
        jPanel_Pc18.add(jLabel64, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 50, 40, 40));

        jLabel65.setForeground(new java.awt.Color(255, 204, 51));
        jLabel65.setText(" Valorant");
        jPanel_Pc18.add(jLabel65, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 110, -1));

        jPanel_JikaPilihKomputer.add(jPanel_Pc18, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 350, 110, 120));

        jPanel1.add(jPanel_JikaPilihKomputer, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 60, 780, 540));

        jPanel_JikaPilihAccount.setBackground(new java.awt.Color(57, 61, 62));
        jPanel_JikaPilihAccount.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable_NamaMember.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Nama", "Harga", "Waktu"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable_NamaMember.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jTable_NamaMember.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable_NamaMemberMouseClicked(evt);
            }
        });
        jScrollPane_NamaMember.setViewportView(jTable_NamaMember);

        jPanel_JikaPilihAccount.add(jScrollPane_NamaMember, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 740, 450));

        jPanel2.setBackground(new java.awt.Color(153, 153, 153));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel66.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel66.setForeground(new java.awt.Color(255, 255, 255));
        jLabel66.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel66.setText("Member");
        jPanel2.add(jLabel66, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 280, 40));

        jPanel_JikaPilihAccount.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, 280, 40));

        jButton_BuatMember.setBackground(new java.awt.Color(51, 255, 51));
        jButton_BuatMember.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton_BuatMember.setForeground(new java.awt.Color(255, 255, 255));
        jButton_BuatMember.setText("Buat Member");
        jButton_BuatMember.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton_BuatMember.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_BuatMemberActionPerformed(evt);
            }
        });
        jPanel_JikaPilihAccount.add(jButton_BuatMember, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 10, 130, 40));

        jPanel_BuatMember.setBackground(new java.awt.Color(255, 255, 255));
        jPanel_BuatMember.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton_BackBuatMember.setBackground(new java.awt.Color(255, 51, 51));
        jButton_BackBuatMember.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton_BackBuatMember.setForeground(new java.awt.Color(255, 255, 255));
        jButton_BackBuatMember.setText("<< Back");
        jButton_BackBuatMember.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton_BackBuatMember.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_BackBuatMemberActionPerformed(evt);
            }
        });
        jPanel_BuatMember.add(jButton_BackBuatMember, new org.netbeans.lib.awtextra.AbsoluteConstraints(595, 390, 90, -1));

        jLabel67.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel67.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel67.setText("Buat Member");
        jPanel_BuatMember.add(jLabel67, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 30, 290, 40));
        jPanel_BuatMember.add(jTextField_UsernameMember, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 120, 290, 30));

        jLabel68.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel68.setText(" Username");
        jPanel_BuatMember.add(jLabel68, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 100, 290, 20));

        jLabel69.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel69.setText(" Password");
        jPanel_BuatMember.add(jLabel69, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 160, 290, 20));

        jLabel70.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel70.setText(" Konfirmasi Password");
        jPanel_BuatMember.add(jLabel70, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 220, 290, 20));

        jButton_BuatMember_2.setBackground(new java.awt.Color(51, 255, 51));
        jButton_BuatMember_2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton_BuatMember_2.setForeground(new java.awt.Color(255, 255, 255));
        jButton_BuatMember_2.setText("Buat Member");
        jButton_BuatMember_2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton_BuatMember_2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_BuatMember_2ActionPerformed(evt);
            }
        });
        jPanel_BuatMember.add(jButton_BuatMember_2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 303, 200, 30));
        jPanel_BuatMember.add(jPasswordField_BuatMember, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 180, 290, 30));
        jPanel_BuatMember.add(jPasswordField_KonfirmasiPasswordMember, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 240, 290, 30));

        jPanel_JikaPilihAccount.add(jPanel_BuatMember, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 720, 430));

        jButton_GantiPassword.setBackground(new java.awt.Color(255, 51, 51));
        jButton_GantiPassword.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton_GantiPassword.setForeground(new java.awt.Color(255, 255, 255));
        jButton_GantiPassword.setText("Ganti Password");
        jButton_GantiPassword.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton_GantiPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_GantiPasswordActionPerformed(evt);
            }
        });
        jPanel_JikaPilihAccount.add(jButton_GantiPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 10, 130, 40));

        jPanel_GantiPassword.setBackground(new java.awt.Color(255, 255, 255));
        jPanel_GantiPassword.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel73.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel73.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel73.setText("Ganti Password");
        jPanel_GantiPassword.add(jLabel73, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 30, 290, 40));

        jLabel74.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel74.setText("Username");
        jPanel_GantiPassword.add(jLabel74, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 100, 290, 20));
        jPanel_GantiPassword.add(jTextField_UsernameGantiPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 120, 290, 30));

        jLabel75.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel75.setText("Password Lama");
        jPanel_GantiPassword.add(jLabel75, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 160, 290, 20));
        jPanel_GantiPassword.add(jPasswordField_PasswordLamaGantiPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 180, 290, 30));

        jLabel76.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel76.setText("Password Baru");
        jPanel_GantiPassword.add(jLabel76, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 220, 290, 20));
        jPanel_GantiPassword.add(jPasswordField_PasswordBaruGantiPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 240, 290, 30));

        jButton_GantiPassword_2.setBackground(new java.awt.Color(255, 51, 51));
        jButton_GantiPassword_2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton_GantiPassword_2.setForeground(new java.awt.Color(255, 255, 255));
        jButton_GantiPassword_2.setText("Ganti Password");
        jButton_GantiPassword_2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton_GantiPassword_2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_GantiPassword_2ActionPerformed(evt);
            }
        });
        jPanel_GantiPassword.add(jButton_GantiPassword_2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 303, 200, 30));

        jButton_BackGantiPassword.setBackground(new java.awt.Color(255, 51, 51));
        jButton_BackGantiPassword.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton_BackGantiPassword.setForeground(new java.awt.Color(255, 255, 255));
        jButton_BackGantiPassword.setText("<< Back");
        jButton_BackGantiPassword.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton_BackGantiPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_BackGantiPasswordActionPerformed(evt);
            }
        });
        jPanel_GantiPassword.add(jButton_BackGantiPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(595, 390, 90, -1));

        jPanel_JikaPilihAccount.add(jPanel_GantiPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 720, 430));

        jPanel_TambahWaktu.setBackground(new java.awt.Color(255, 255, 255));
        jPanel_TambahWaktu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel77.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel77.setText("Username");
        jPanel_TambahWaktu.add(jLabel77, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 100, 110, 30));

        jTextField_UsernameTambahWaktu.setEditable(false);
        jTextField_UsernameTambahWaktu.setBackground(new java.awt.Color(255, 255, 255));
        jPanel_TambahWaktu.add(jTextField_UsernameTambahWaktu, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 130, 220, 30));

        jLabel78.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel78.setText("Paket");
        jPanel_TambahWaktu.add(jLabel78, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 170, 70, 30));

        jComboBox_Paket.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Paket 1 Jam", "Paket 2 Jam", "Paket 3 Jam", "Paket 5 Jam", "Paket 10 Jam", "Paket Malam" }));
        jComboBox_Paket.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox_PaketActionPerformed(evt);
            }
        });
        jPanel_TambahWaktu.add(jComboBox_Paket, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 200, 140, -1));

        jLabel79.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel79.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel79.setText("Isi Paket");
        jPanel_TambahWaktu.add(jLabel79, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 30, 290, 40));

        jLabel80.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel80.setText("Harga");
        jPanel_TambahWaktu.add(jLabel80, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 230, 70, 30));

        jTextField_HargaTambahWaktu.setEditable(false);
        jTextField_HargaTambahWaktu.setBackground(new java.awt.Color(255, 255, 255));
        jPanel_TambahWaktu.add(jTextField_HargaTambahWaktu, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 260, 220, 30));

        jButton_IsiWaktu.setBackground(new java.awt.Color(51, 255, 51));
        jButton_IsiWaktu.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton_IsiWaktu.setForeground(new java.awt.Color(255, 255, 255));
        jButton_IsiWaktu.setText("Isi");
        jButton_IsiWaktu.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton_IsiWaktu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_IsiWaktuActionPerformed(evt);
            }
        });
        jPanel_TambahWaktu.add(jButton_IsiWaktu, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 360, 200, 30));

        jButton_BackTambahWaktu.setBackground(new java.awt.Color(255, 51, 51));
        jButton_BackTambahWaktu.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton_BackTambahWaktu.setForeground(new java.awt.Color(255, 255, 255));
        jButton_BackTambahWaktu.setText("<< Back");
        jButton_BackTambahWaktu.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton_BackTambahWaktu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_BackTambahWaktuActionPerformed(evt);
            }
        });
        jPanel_TambahWaktu.add(jButton_BackTambahWaktu, new org.netbeans.lib.awtextra.AbsoluteConstraints(595, 390, 90, -1));

        jPanel_JikaPilihAccount.add(jPanel_TambahWaktu, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 720, 430));

        jPanel1.add(jPanel_JikaPilihAccount, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 60, 780, 540));

        jPanel_JikaPilihTransaksi.setBackground(new java.awt.Color(57, 61, 62));
        jPanel_JikaPilihTransaksi.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable_Transaksi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Tanggal", "Username", "Harga", "Waktu"
            }
        ));
        jScrollPane_Transaksi.setViewportView(jTable_Transaksi);

        jPanel_JikaPilihTransaksi.add(jScrollPane_Transaksi, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 940, 420));

        jLabel71.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel71.setForeground(new java.awt.Color(255, 255, 255));
        jLabel71.setText("Total Pemasukan  :");
        jPanel_JikaPilihTransaksi.add(jLabel71, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 470, 170, 40));

        jLabel_HargaTransaksi.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel_HargaTransaksi.setForeground(new java.awt.Color(255, 255, 255));
        jPanel_JikaPilihTransaksi.add(jLabel_HargaTransaksi, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 466, 150, 50));

        jPanel1.add(jPanel_JikaPilihTransaksi, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 1000, 540));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 600));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel_TulisanKomputerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_TulisanKomputerMouseClicked
        // Menghitamkan Background komputer, selain komputer akan berubah menjadi warna biru
        jPanel_Komputer.setBackground(new Color(49,51,63));
        jPanel_Account.setBackground(new Color(48,119,167));
        jPanel_Transaksi.setBackground(new Color(48,119,167));
        
        // Membirukan foreground(Warna Tulisan) Komputer, Selain komputer akan berubah menjadi warna putih
        jLabel_TulisanKomputer.setForeground(new Color(61,122,167));
        jLabel_TulisanAccount.setForeground(Color.white);
        jLabel_TulisanTransaksi.setForeground(Color.white);
        
        // Mengaktifkan Panel Komputer
        jPanel_JikaPilihKomputer.setVisible(true);
        jPanel_JikaPilihAccount.setVisible(false);
        jPanel_JikaPilihTransaksi.setVisible(false);
        jPanel_PendapatanHarian.setVisible(true);
        jPanel_SearchNamaMember.setVisible(false);
        jPanel_JikaPilihAccount.setVisible(false);
        jPanel_JikaPilihTransaksi.setVisible(false);
    }//GEN-LAST:event_jLabel_TulisanKomputerMouseClicked

    private void jLabel_TulisanAccountMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_TulisanAccountMouseClicked
        // Menghitamkan Background Account, selain Account akan berubah menjadi warna biru
        tampilanMember();
        jPanel_Account.setBackground(new Color(49,51,63));
        jPanel_Komputer.setBackground(new Color(48,119,167));
        jPanel_Transaksi.setBackground(new Color(48,119,167));
        
        // Membirukan foreground(Warna Tulisan) Account, Selain Account akan berubah menjadi warna putih
        jLabel_TulisanAccount.setForeground(new Color(61,122,167));
        jLabel_TulisanKomputer.setForeground(Color.white);
        jLabel_TulisanTransaksi.setForeground(Color.white);
        
        
        // Mengaktifkan Panel Account
        jPanel_JikaPilihAccount.setVisible(true);
        jPanel_SearchNamaMember.setVisible(true);
        jPanel_PendapatanHarian.setVisible(false);
        jPanel_JikaPilihKomputer.setVisible(false);
        jPanel_JikaPilihTransaksi.setVisible(false);
        
        // Mengaktifkan 
        jTextField1.setVisible(true);
        jTextField_SearchMember.setVisible(true);
        jButton_Cari.setVisible(true);
        jScrollPane_NamaMember.setVisible(true);
        jButton_BuatMember.setVisible(true);
        
        jPanel_TambahWaktu.setVisible(false);
    }//GEN-LAST:event_jLabel_TulisanAccountMouseClicked

    private void jLabel_TulisanTransaksiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_TulisanTransaksiMouseClicked
        tampilanTransaksi();
        jumlahTransaksi();
        // Menghitamkan Background Transaksi, selain Transaksi akan berubah menjadi warna biru
        jPanel_Transaksi.setBackground(new Color(49,51,63));
        jPanel_Komputer.setBackground(new Color(48,119,167));
        jPanel_Account.setBackground(new Color(48,119,167));
        
        // Membirukan foreground(Warna Tulisan) Transaksi, Selain Transaksi akan berubah menjadi warna putih
        jLabel_TulisanTransaksi.setForeground(new Color(61,122,167));
        jLabel_TulisanKomputer.setForeground(Color.white);
        jLabel_TulisanAccount.setForeground(Color.white);
        
        
        // Mengaktifkan Panel Transaksi
        jPanel_JikaPilihTransaksi.setVisible(true);
        jPanel_JikaPilihKomputer.setVisible(false);
        jPanel_JikaPilihAccount.setVisible(false);
        jPanel_PendapatanHarian.setVisible(false);
        jPanel_SearchNamaMember.setVisible(false);
        
        // Mengaktifkan
        jScrollPane_Transaksi.setVisible(true);
    }//GEN-LAST:event_jLabel_TulisanTransaksiMouseClicked

    private void jButton_BuatMemberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_BuatMemberActionPerformed
        jPanel_BuatMember.setVisible(true);
        jButton_BackBuatMember.setVisible(true);
        jButton_BuatMember_2.setVisible(true);
        // Mengaktifkan Text Field
        jTextField_UsernameMember.setVisible(true);
        jPasswordField_BuatMember.setVisible(true);
        jPasswordField_KonfirmasiPasswordMember.setVisible(true);
        
        jScrollPane_NamaMember.setVisible(false);
        jPanel_GantiPassword.setVisible(false);
    }//GEN-LAST:event_jButton_BuatMemberActionPerformed

    private void jButton_BackBuatMemberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_BackBuatMemberActionPerformed
        jScrollPane_NamaMember.setVisible(true);
        jPanel_BuatMember.setVisible(false);
    }//GEN-LAST:event_jButton_BackBuatMemberActionPerformed

    private void jButton_LogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_LogoutActionPerformed
        this.dispose();
        Option_Admin_Customer option = new Option_Admin_Customer();
        option.setVisible(true);
    }//GEN-LAST:event_jButton_LogoutActionPerformed

    private void jButton_BuatMember_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_BuatMember_2ActionPerformed
        try {
            String username = jTextField_UsernameMember.getText();
            String password = jPasswordField_BuatMember.getText();
            String konfirmasiPassword = jPasswordField_KonfirmasiPasswordMember.getText();

            if (password.equals(konfirmasiPassword)) {
                String sql = "INSERT INTO datamember VALUES (?, ?)";
                String tambahSql = "INSERT INTO tbl_akun (Username, Harga, Waktu) VALUES (?, 0, 0)";

                java.sql.Connection conn = (Connection) KoneksiDataMember.configDB();
                java.sql.PreparedStatement pst = conn.prepareStatement(sql);
                java.sql.PreparedStatement pst1 = conn.prepareStatement(tambahSql);

                pst.setString(1, username);
                pst.setString(2, password);
                pst.execute();

                pst1.setString(1, username);
                int rowsAffected = pst1.executeUpdate();

                if (rowsAffected > 0) {
                    JOptionPane.showMessageDialog(this, "Data Dengan Nama " + username + " Berhasil Disimpan");
                } else {
                    JOptionPane.showMessageDialog(this, "Gagal Menambahkan Data");
                }
            } else {
                JOptionPane.showMessageDialog(this, "Masukkan Konfirmasi Password Dengan Benar");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_jButton_BuatMember_2ActionPerformed

    private void jTable_NamaMemberMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable_NamaMemberMouseClicked
        int index = jTable_NamaMember.getSelectedRow();
        DefaultTableModel model = (DefaultTableModel) jTable_NamaMember.getModel();
        
        int notif1 = JOptionPane.showConfirmDialog(this, "Apakah Anda Ingin Menambahkan Waktu ? ");
        switch (notif1) {
            case JOptionPane.YES_OPTION -> {
                jScrollPane_NamaMember.setVisible(false);
                jPanel_TambahWaktu.setVisible(true);
                jTextField_UsernameTambahWaktu.setText(model.getValueAt(index, 0).toString());
            }
            case JOptionPane.CANCEL_OPTION -> {
                jScrollPane_NamaMember.setVisible(true);
            }        
        }
//        int index = jTable_NamaMember.getSelectedRow();
//        DefaultTableModel model = (DefaultTableModel) jTable_NamaMember.getModel();
//
//        String value1 = model.getValueAt(index, 0).toString();
//        String value2 = model.getValueAt(index, 1).toString();
//        String value3 = model.getValueAt(index, 2).toString();
//        String value4 = model.getValueAt(index, 3).toString();
//

//        tampilanMember();
//        int baris = jTable_NamaMember.rowAtPoint(evt.getPoint());
//        
//        String Username = jTable_NamaMember.getValueAt(baris, 1).toString();
//        jTextField_UsernameMember.setText(Username);
//        
//        String Password = jTable_NamaMember.getValueAt(baris, 2).toString();
//        jPasswordField_BuatMember.setText(Password);
                
    }//GEN-LAST:event_jTable_NamaMemberMouseClicked

    private void jButton_GantiPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_GantiPasswordActionPerformed
        jPanel_GantiPassword.setVisible(true);
        
        jPanel_BuatMember.setVisible(false);
        jScrollPane_NamaMember.setVisible(false);
    }//GEN-LAST:event_jButton_GantiPasswordActionPerformed

    private void jButton_BackGantiPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_BackGantiPasswordActionPerformed
        jScrollPane_NamaMember.setVisible(true);
        jPanel_GantiPassword.setVisible(false);
    }//GEN-LAST:event_jButton_BackGantiPasswordActionPerformed

    private void jButton_GantiPassword_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_GantiPassword_2ActionPerformed
        try {
            String username = jTextField_UsernameGantiPassword.getText();
            String passwordLama = jPasswordField_PasswordLamaGantiPassword.getText();
            String passwordBaru = jPasswordField_PasswordBaruGantiPassword.getText();

            String sql = "SELECT * FROM datamember WHERE Username = ?";
            String sql1 = "UPDATE datamember SET Password = ? WHERE Username = ?";

            java.sql.Connection conn = (Connection) KoneksiDataMember.configDB();
            java.sql.PreparedStatement pstm = conn.prepareStatement(sql);
            java.sql.PreparedStatement pstm1 = conn.prepareStatement(sql1);

            pstm.setString(1, username);
            ResultSet resultSet = pstm.executeQuery();

            if (resultSet.next()) {
                String existingPassword = resultSet.getString("Password");
                if (existingPassword.equals(passwordLama)) {
                    pstm1.setString(1, passwordBaru);
                    pstm1.setString(2, username);
                    int rowsUpdated = pstm1.executeUpdate();

                    if (rowsUpdated > 0) {
                        JOptionPane.showMessageDialog(this, "Password Baru Berhasil Diganti");
                    } else {
                        JOptionPane.showMessageDialog(this, "Gagal Mengganti Password");
                    }
                } else {
                    JOptionPane.showMessageDialog(this, "Password Lama Salah");
                }
            } else {
                JOptionPane.showMessageDialog(this, "Username Tidak Ditemukan");
            }

            conn.close();

        } catch (HeadlessException | SQLException e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }

    }//GEN-LAST:event_jButton_GantiPassword_2ActionPerformed

    private void jButton_BackTambahWaktuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_BackTambahWaktuActionPerformed
        jPanel_TambahWaktu.setVisible(false);
        jScrollPane_NamaMember.setVisible(true);
    }//GEN-LAST:event_jButton_BackTambahWaktuActionPerformed

    private void jComboBox_PaketActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox_PaketActionPerformed
        switch (jComboBox_Paket.getSelectedIndex()) {
            case 0:
                jTextField_HargaTambahWaktu.setText("Rp. 10.000");
                break;
            case 1:
                jTextField_HargaTambahWaktu.setText("Rp. 18.000");
                break;
            case 2:
                jTextField_HargaTambahWaktu.setText("Rp. 25.000");
                break;
            case 3:
                jTextField_HargaTambahWaktu.setText("Rp. 35.000");
                break;
            case 4:
                jTextField_HargaTambahWaktu.setText("Rp. 50.000");
                break;
            case 5:
                jTextField_HargaTambahWaktu.setText("Rp. 40.000");
                break;
        }
    }//GEN-LAST:event_jComboBox_PaketActionPerformed

    private void jButton_IsiWaktuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_IsiWaktuActionPerformed
        double harga1jam = 10000;
        double harga2jam = 18000;
        double harga3jam = 25000;
        double harga5jam = 35000;
        double harga10jam = 50000;
        
        Time waktu1jam = Time.valueOf("01:00:00");
        Time waktu2jam = Time.valueOf("02:00:00");
        Time waktu3jam = Time.valueOf("03:00:00");
        Time waktu5jam = Time.valueOf("05:00:00");
        Time waktu10jam = Time.valueOf("10:00:00");
        
        try {
            String User = jTextField_UsernameTambahWaktu.getText();
            int pilihan = jComboBox_Paket.getSelectedIndex();
            
            String selectsql = "SELECT Harga,Waktu FROM tbl_akun WHERE Username = ?";
            String transaksisql = "INSERT INTO tbl_transaksi VALUES (?,?,?,?)";
            
            Date date = new Date();
            Timestamp currentDate = new Timestamp(date.getTime());
            
            java.sql.Connection conn = (Connection) KoneksiDataMember.configDB();
            java.sql.PreparedStatement pstm1 = conn.prepareStatement(selectsql);
            java.sql.PreparedStatement pstmTransaksi = conn.prepareStatement(transaksisql);
            

            pstm1.setString(1, User);
            ResultSet rs2 = pstm1.executeQuery();
      
            switch (pilihan) {
                case 0 :
                    pstmTransaksi.setTimestamp(1, currentDate);
                    pstmTransaksi.setString(2, User);
                    pstmTransaksi.setDouble(3, harga1jam);
                    pstmTransaksi.setTime(4, waktu1jam);
                    pstmTransaksi.execute();
                    
                    if (rs2.next()) {
                        String updatesql1jam = "UPDATE tbl_akun SET Harga = Harga + ? ,Waktu = ADDTIME(Waktu, '01:00:00') WHERE Username = ? ";
                        java.sql.PreparedStatement statement = conn.prepareStatement(updatesql1jam);
                        statement.setDouble(1, harga1jam);
                        statement.setString(2, User);
                        int rowsAffected = statement.executeUpdate();

                        if (rowsAffected > 0) {
                            JOptionPane.showMessageDialog(this, "1 Jam Telah Masuk Ke Data");
                        } else {
                            JOptionPane.showMessageDialog(this, "Data Gagal");
                        }
                        statement.close();
                    }
                    break;
                    
                case 1 :
                    pstmTransaksi.setTimestamp(1, currentDate);
                    pstmTransaksi.setString(2, User);
                    pstmTransaksi.setDouble(3, harga2jam);
                    pstmTransaksi.setTime(4, waktu2jam);
                    pstmTransaksi.execute();
                    if (rs2.next()) {
                        String updatesql2jam = "UPDATE tbl_akun SET Harga = Harga + ? ,Waktu = ADDTIME(Waktu, '02:00:00') WHERE Username = ? ";
                        java.sql.PreparedStatement statement = conn.prepareStatement(updatesql2jam);
                        statement.setDouble(1, harga2jam);
                        statement.setString(2, User);
                        int rowsAffected = statement.executeUpdate();

                        if (rowsAffected > 0) {
                            JOptionPane.showMessageDialog(this, "2 Jam Telah Masuk Ke Data");
                        } else {
                            JOptionPane.showMessageDialog(this, "Data Gagal");
                        }
                        statement.close();
                    }
                    break;
                    
                case 2 :
                    pstmTransaksi.setTimestamp(1, currentDate);
                    pstmTransaksi.setString(2, User);
                    pstmTransaksi.setDouble(3, harga3jam);
                    pstmTransaksi.setTime(4, waktu3jam);
                    pstmTransaksi.execute();
                    if (rs2.next()) {
                        String updatesql3jam = "UPDATE tbl_akun SET Harga = Harga + ? ,Waktu = ADDTIME(Waktu, '03:00:00') WHERE Username = ? ";
                        java.sql.PreparedStatement statement = conn.prepareStatement(updatesql3jam);
                        statement.setDouble(1, harga3jam);
                        statement.setString(2, User);
                        int rowsAffected = statement.executeUpdate();

                        if (rowsAffected > 0) {
                            JOptionPane.showMessageDialog(this, "3 Jam Telah Masuk Ke Data");
                        } else {
                            JOptionPane.showMessageDialog(this, "Data Gagal");
                        }
                        statement.close();
                    }
                    break;
                    
                case 3 :
                    pstmTransaksi.setTimestamp(1, currentDate);
                    pstmTransaksi.setString(2, User);
                    pstmTransaksi.setDouble(3, harga5jam);
                    pstmTransaksi.setTime(4, waktu5jam);
                    pstmTransaksi.execute();
                    if (rs2.next()) {
                        String updatesql5jam = "UPDATE tbl_akun SET Harga = Harga + ? ,Waktu = ADDTIME(Waktu, '05:00:00') WHERE Username = ? ";
                        java.sql.PreparedStatement statement = conn.prepareStatement(updatesql5jam);
                        statement.setDouble(1, harga5jam);
                        statement.setString(2, User);
                        int rowsAffected = statement.executeUpdate();

                        if (rowsAffected > 0) {
                            JOptionPane.showMessageDialog(this, "5 Jam Telah Masuk Ke Data");
                        } else {
                            JOptionPane.showMessageDialog(this, "Data Gagal");
                        }
                        statement.close();
                    }               
                    break;
                    
                case 4 :
                    pstmTransaksi.setTimestamp(1, currentDate);
                    pstmTransaksi.setString(2, User);
                    pstmTransaksi.setDouble(3, harga10jam);
                    pstmTransaksi.setTime(4, waktu10jam);
                    pstmTransaksi.execute();
                    if (rs2.next()) {
                        String updatesql10jam = "UPDATE tbl_akun SET Harga = Harga + ? ,Waktu = ADDTIME(Waktu, '10:00:00') WHERE Username = ? ";
                        java.sql.PreparedStatement statement = conn.prepareStatement(updatesql10jam);
                        statement.setDouble(1, harga10jam);
                        statement.setString(2, User);
                        int rowsAffected = statement.executeUpdate();

                        if (rowsAffected > 0) {
                            JOptionPane.showMessageDialog(this, "10 Jam Telah Masuk Ke Data");
                        } else {
                            JOptionPane.showMessageDialog(this, "Data Gagal");
                        }
                        statement.close();
                    }
                    break;
                    
                case 5 :
                    JOptionPane.showMessageDialog(this, "Maaf Untuk Saat ini, Paket Malam Sedang Tidak Bisa");
                    break;
            }
            
            conn.close();

        
        } catch (Exception e){
            e.printStackTrace();
            JOptionPane.showMessageDialog(null, "Data Gagal Ditampilkan");
        }
        
        
    }//GEN-LAST:event_jButton_IsiWaktuActionPerformed

    private void jTextField_SearchMemberKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_SearchMemberKeyReleased
        tampilanMember();
    }//GEN-LAST:event_jTextField_SearchMemberKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Admin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_BackBuatMember;
    private javax.swing.JButton jButton_BackGantiPassword;
    private javax.swing.JButton jButton_BackTambahWaktu;
    private javax.swing.JButton jButton_BuatMember;
    private javax.swing.JButton jButton_BuatMember_2;
    private javax.swing.JButton jButton_Cari;
    private javax.swing.JButton jButton_GantiPassword;
    private javax.swing.JButton jButton_GantiPassword_2;
    private javax.swing.JButton jButton_IsiWaktu;
    private javax.swing.JButton jButton_Logout;
    private javax.swing.JComboBox<String> jComboBox_Paket;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JLabel jLabel54;
    private javax.swing.JLabel jLabel55;
    private javax.swing.JLabel jLabel56;
    private javax.swing.JLabel jLabel57;
    private javax.swing.JLabel jLabel58;
    private javax.swing.JLabel jLabel59;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel60;
    private javax.swing.JLabel jLabel61;
    private javax.swing.JLabel jLabel62;
    private javax.swing.JLabel jLabel63;
    private javax.swing.JLabel jLabel64;
    private javax.swing.JLabel jLabel65;
    private javax.swing.JLabel jLabel66;
    private javax.swing.JLabel jLabel67;
    private javax.swing.JLabel jLabel68;
    private javax.swing.JLabel jLabel69;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel70;
    private javax.swing.JLabel jLabel71;
    private javax.swing.JLabel jLabel73;
    private javax.swing.JLabel jLabel74;
    private javax.swing.JLabel jLabel75;
    private javax.swing.JLabel jLabel76;
    private javax.swing.JLabel jLabel77;
    private javax.swing.JLabel jLabel78;
    private javax.swing.JLabel jLabel79;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel80;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabel_DetailPc;
    private javax.swing.JLabel jLabel_HargaTransaksi;
    private javax.swing.JLabel jLabel_TulisanAccount;
    private javax.swing.JLabel jLabel_TulisanKomputer;
    private javax.swing.JLabel jLabel_TulisanTransaksi;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel_Account;
    private javax.swing.JPanel jPanel_BuatMember;
    private javax.swing.JPanel jPanel_GantiPassword;
    private javax.swing.JPanel jPanel_HeaderAdminWarnet;
    private javax.swing.JPanel jPanel_JikaPilihAccount;
    private javax.swing.JPanel jPanel_JikaPilihKomputer;
    private javax.swing.JPanel jPanel_JikaPilihTransaksi;
    private javax.swing.JPanel jPanel_Komputer;
    private javax.swing.JPanel jPanel_Pc01;
    private javax.swing.JPanel jPanel_Pc02;
    private javax.swing.JPanel jPanel_Pc03;
    private javax.swing.JPanel jPanel_Pc04;
    private javax.swing.JPanel jPanel_Pc05;
    private javax.swing.JPanel jPanel_Pc06;
    private javax.swing.JPanel jPanel_Pc07;
    private javax.swing.JPanel jPanel_Pc08;
    private javax.swing.JPanel jPanel_Pc09;
    private javax.swing.JPanel jPanel_Pc10;
    private javax.swing.JPanel jPanel_Pc11;
    private javax.swing.JPanel jPanel_Pc12;
    private javax.swing.JPanel jPanel_Pc13;
    private javax.swing.JPanel jPanel_Pc14;
    private javax.swing.JPanel jPanel_Pc15;
    private javax.swing.JPanel jPanel_Pc16;
    private javax.swing.JPanel jPanel_Pc17;
    private javax.swing.JPanel jPanel_Pc18;
    private javax.swing.JPanel jPanel_PendapatanHarian;
    private javax.swing.JPanel jPanel_SearchNamaMember;
    private javax.swing.JPanel jPanel_TambahWaktu;
    private javax.swing.JPanel jPanel_Transaksi;
    private javax.swing.JPasswordField jPasswordField_BuatMember;
    private javax.swing.JPasswordField jPasswordField_KonfirmasiPasswordMember;
    private javax.swing.JPasswordField jPasswordField_PasswordBaruGantiPassword;
    private javax.swing.JPasswordField jPasswordField_PasswordLamaGantiPassword;
    private javax.swing.JScrollPane jScrollPane_NamaMember;
    private javax.swing.JScrollPane jScrollPane_Transaksi;
    private javax.swing.JTable jTable_NamaMember;
    private javax.swing.JTable jTable_Transaksi;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField_HargaTambahWaktu;
    private javax.swing.JTextField jTextField_SearchMember;
    private javax.swing.JTextField jTextField_UsernameGantiPassword;
    private javax.swing.JTextField jTextField_UsernameMember;
    private javax.swing.JTextField jTextField_UsernameTambahWaktu;
    // End of variables declaration//GEN-END:variables
}
