/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package projectwarnet;
import java.sql.Connection;
import java.awt.Desktop;
import java.awt.Image;
import java.awt.Toolkit;
import java.awt.event.WindowEvent;
import java.io.IOException;
import java.net.URI;
import java.net.URISyntaxException;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.*;

/**
 *
 * @author Reyhan Al Farel
 */
public class Login extends javax.swing.JFrame {
    
    public static String username;
    
    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
        
    }
    
    public void close() {
        WindowEvent closeWindow = new WindowEvent(this, WindowEvent.WINDOW_CLOSING);
        Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(closeWindow);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel_GambarKomputer = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField_Username = new javax.swing.JTextField();
        jPassword_Password = new javax.swing.JPasswordField();
        jCheckBox1 = new javax.swing.JCheckBox();
        jButton_Login = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel_Daftar = new javax.swing.JLabel();
        jLabel_Whatsapp = new javax.swing.JLabel();
        jLabel_Facebook = new javax.swing.JLabel();
        jLabel_Instagram = new javax.swing.JLabel();
        jPanel_Atas = new javax.swing.JPanel();
        jPanel_Bawah = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setPreferredSize(new java.awt.Dimension(300, 450));

        jLabel_GambarKomputer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Gambar Komputer For Login.jpg"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel_GambarKomputer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel_GambarKomputer, javax.swing.GroupLayout.PREFERRED_SIZE, 244, Short.MAX_VALUE)
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setPreferredSize(new java.awt.Dimension(300, 450));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Login");

        jLabel2.setText("Belum Punya Member ?");

        jTextField_Username.setText("Username");
        jTextField_Username.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 0, 0)));
        jTextField_Username.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jTextField_Username.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextField_UsernameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField_UsernameFocusLost(evt);
            }
        });

        jPassword_Password.setText("Password");
        jPassword_Password.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 0, 0)));
        jPassword_Password.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jPassword_PasswordFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jPassword_PasswordFocusLost(evt);
            }
        });

        jCheckBox1.setText("Ingat Saya?");

        jButton_Login.setBackground(new java.awt.Color(21, 47, 70));
        jButton_Login.setForeground(new java.awt.Color(255, 255, 255));
        jButton_Login.setText("Login");
        jButton_Login.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton_Login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_LoginActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        jLabel3.setText("About Us");

        jLabel_Daftar.setText("Daftar");
        jLabel_Daftar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel_Daftar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_DaftarMouseClicked(evt);
            }
        });

        jLabel_Whatsapp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8-whatsapp-48.png"))); // NOI18N
        jLabel_Whatsapp.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel_Whatsapp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_WhatsappMouseClicked(evt);
            }
        });

        jLabel_Facebook.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8-facebook-48.png"))); // NOI18N
        jLabel_Facebook.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel_Facebook.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_FacebookMouseClicked(evt);
            }
        });

        jLabel_Instagram.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8-instagram-48.png"))); // NOI18N
        jLabel_Instagram.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel_Instagram.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_InstagramMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel_Whatsapp)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel_Facebook)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel_Instagram))
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addComponent(jLabel2)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jLabel_Daftar))
                                .addComponent(jTextField_Username)
                                .addComponent(jPassword_Password, javax.swing.GroupLayout.DEFAULT_SIZE, 249, Short.MAX_VALUE))
                            .addComponent(jButton_Login, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jCheckBox1))))
                .addContainerGap(27, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel_Daftar))
                .addGap(37, 37, 37)
                .addComponent(jTextField_Username, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51)
                .addComponent(jPassword_Password, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jCheckBox1)
                .addGap(31, 31, 31)
                .addComponent(jButton_Login)
                .addGap(30, 30, 30)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel_Facebook, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel_Instagram, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel_Whatsapp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(8, Short.MAX_VALUE))
        );

        jPanel_Atas.setBackground(new java.awt.Color(21, 47, 70));

        javax.swing.GroupLayout jPanel_AtasLayout = new javax.swing.GroupLayout(jPanel_Atas);
        jPanel_Atas.setLayout(jPanel_AtasLayout);
        jPanel_AtasLayout.setHorizontalGroup(
            jPanel_AtasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
        jPanel_AtasLayout.setVerticalGroup(
            jPanel_AtasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel_Bawah.setBackground(new java.awt.Color(21, 47, 70));

        javax.swing.GroupLayout jPanel_BawahLayout = new javax.swing.GroupLayout(jPanel_Bawah);
        jPanel_Bawah.setLayout(jPanel_BawahLayout);
        jPanel_BawahLayout.setHorizontalGroup(
            jPanel_BawahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
        jPanel_BawahLayout.setVerticalGroup(
            jPanel_BawahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel_Atas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel_Bawah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 318, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel_Atas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel_Bawah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 462, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField_UsernameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField_UsernameFocusGained
        if (jTextField_Username.getText().equals("Username")) {
            jTextField_Username.setText("");
        }
    }//GEN-LAST:event_jTextField_UsernameFocusGained

    private void jTextField_UsernameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField_UsernameFocusLost
        if (jTextField_Username.getText().equals("")) {
            jTextField_Username.setText("Username");
        }
    }//GEN-LAST:event_jTextField_UsernameFocusLost

    private void jPassword_PasswordFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jPassword_PasswordFocusGained
        if (jPassword_Password.getText().equals("Password")) {
            jPassword_Password.setText("");
        }
    }//GEN-LAST:event_jPassword_PasswordFocusGained

    private void jPassword_PasswordFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jPassword_PasswordFocusLost
        if (jPassword_Password.getText().equals("")) {
            jPassword_Password.setText("Password");
        }
    }//GEN-LAST:event_jPassword_PasswordFocusLost

    private void jButton_LoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_LoginActionPerformed
        try {
            username = jTextField_Username.getText();
            String password = jPassword_Password.getText();
            
            String sql = "SELECT * FROM datamember WHERE Username=('"+jTextField_Username.getText()+"')AND Password = ('"+jPassword_Password.getText()+"')";
            java.sql.Connection conn =(Connection)KoneksiDataMember.configDB();
            java.sql.PreparedStatement pst = conn.prepareStatement(sql);
            java.sql.ResultSet rs = pst.executeQuery(sql);
            if (rs.next()) {
                if (jTextField_Username.getText().equals(rs.getString("Username")) && jPassword_Password.getText().equals(rs.getString("Password"))) {
                    JOptionPane.showMessageDialog(null, "Login Berhasil");
                    this.setVisible(false);
                    ProgramWarnet warnet = new ProgramWarnet();
                    warnet.setVisible(true);
                    warnet.setDefaultCloseOperation(Login.EXIT_ON_CLOSE);
                }
            } else {
                JOptionPane.showMessageDialog(null, "Username Atau Password Tidak Ditemukan");
            }
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_jButton_LoginActionPerformed

    private void jLabel_DaftarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_DaftarMouseClicked
        //close();
        this.dispose();
        Register reg = new Register();
        reg.setVisible(true);
        reg.setDefaultCloseOperation(Register.EXIT_ON_CLOSE);
        
    }//GEN-LAST:event_jLabel_DaftarMouseClicked

    private void jLabel_WhatsappMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_WhatsappMouseClicked
        // Menuju ke Whatsapp Fiko Haritz XD
        Desktop browser_wa = Desktop.getDesktop();
        try {
            browser_wa.browse(new URI("https://wa.me/6281296416805"));
            
        } catch (IOException err) {
        
        } catch (URISyntaxException err) {
            
        }
    }//GEN-LAST:event_jLabel_WhatsappMouseClicked

    private void jLabel_FacebookMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_FacebookMouseClicked
        // Menuju Ke Facebook Fiko Haitz XD
        Desktop browser_fb = Desktop.getDesktop();
        try {
            browser_fb.browse(new URI("https://www.facebook.com/muhammad.haritzi"));
            
        } catch (IOException err) {
        
        } catch (URISyntaxException err) {
            
        }
    }//GEN-LAST:event_jLabel_FacebookMouseClicked

    private void jLabel_InstagramMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_InstagramMouseClicked
        // Menuju Ke Instagram Fiko Haritz XD
        Desktop browser_ig = Desktop.getDesktop();
        try {
            browser_ig.browse(new URI("https://www.instagram.com/fikoharitz/"));
            
        } catch (IOException err) {
        
        } catch (URISyntaxException err) {
            
        }
    }//GEN-LAST:event_jLabel_InstagramMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_Login;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel_Daftar;
    private javax.swing.JLabel jLabel_Facebook;
    private javax.swing.JLabel jLabel_GambarKomputer;
    private javax.swing.JLabel jLabel_Instagram;
    private javax.swing.JLabel jLabel_Whatsapp;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel_Atas;
    private javax.swing.JPanel jPanel_Bawah;
    private javax.swing.JPasswordField jPassword_Password;
    private javax.swing.JTextField jTextField_Username;
    // End of variables declaration//GEN-END:variables
}
